services:
  - docker

branches:
  only:
  - master
  - develop

language: java

jdk: oraclejdk8

install: true

before_script:
  - echo "Starting build"

script:
  - mvn clean package

after_success:
  - sh deploy_dockerhub.sh